/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KonkurrencerRouteImport } from './routes/konkurrencer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KonkurrencerRoute = KonkurrencerRouteImport.update({
  id: '/konkurrencer',
  path: '/konkurrencer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/konkurrencer': typeof KonkurrencerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/konkurrencer': typeof KonkurrencerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/konkurrencer': typeof KonkurrencerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/konkurrencer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/konkurrencer'
  id: '__root__' | '/' | '/konkurrencer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KonkurrencerRoute: typeof KonkurrencerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konkurrencer': {
      id: '/konkurrencer'
      path: '/konkurrencer'
      fullPath: '/konkurrencer'
      preLoaderRoute: typeof KonkurrencerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KonkurrencerRoute: KonkurrencerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
