/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KanoerRouteImport } from './routes/kanoer'
import { Route as OversigtRouteImport } from './routes/oversigt'
import { Route as ScoresRouteImport } from './routes/scores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KanoerRoute = KanoerRouteImport.update({
  id: '/kanoer',
  path: '/kanoer',
  getParentRoute: () => rootRouteImport,
} as any)
const OversigtRoute = OversigtRouteImport.update({
  id: '/oversigt',
  path: '/oversigt',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kanoer': typeof KanoerRoute
  '/oversigt': typeof OversigtRoute
  '/scores': typeof ScoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kanoer': typeof KanoerRoute
  '/oversigt': typeof OversigtRoute
  '/scores': typeof ScoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kanoer': typeof KanoerRoute
  '/oversigt': typeof OversigtRoute
  '/scores': typeof ScoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kanoer' | '/oversigt' | '/scores'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kanoer' | '/oversigt' | '/scores'
  id: '__root__' | '/' | '/kanoer' | '/oversigt' | '/scores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KanoerRoute: typeof KanoerRoute
  OversigtRoute: typeof OversigtRoute
  ScoresRoute: typeof ScoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanoer': {
      id: '/kanoer'
      path: '/kanoer'
      fullPath: '/kanoer'
      preLoaderRoute: typeof KanoerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oversigt': {
      id: '/oversigt'
      path: '/oversigt'
      fullPath: '/oversigt'
      preLoaderRoute: typeof OversigtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KanoerRoute: KanoerRoute,
  OversigtRoute: OversigtRoute,
  ScoresRoute: ScoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
