/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistorikRouteImport } from './routes/historik'
import { Route as KanoerRouteImport } from './routes/kanoer'
import { Route as OpsaetningRouteImport } from './routes/opsaetning'
import { Route as OversigtRouteImport } from './routes/oversigt'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as StillingRouteImport } from './routes/stilling'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorikRoute = HistorikRouteImport.update({
  id: '/historik',
  path: '/historik',
  getParentRoute: () => rootRouteImport,
} as any)
const KanoerRoute = KanoerRouteImport.update({
  id: '/kanoer',
  path: '/kanoer',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsaetningRoute = OpsaetningRouteImport.update({
  id: '/opsaetning',
  path: '/opsaetning',
  getParentRoute: () => rootRouteImport,
} as any)
const OversigtRoute = OversigtRouteImport.update({
  id: '/oversigt',
  path: '/oversigt',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const StillingRoute = StillingRouteImport.update({
  id: '/stilling',
  path: '/stilling',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historik': typeof HistorikRoute
  '/kanoer': typeof KanoerRoute
  '/opsaetning': typeof OpsaetningRoute
  '/oversigt': typeof OversigtRoute
  '/scores': typeof ScoresRoute
  '/stilling': typeof StillingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historik': typeof HistorikRoute
  '/kanoer': typeof KanoerRoute
  '/opsaetning': typeof OpsaetningRoute
  '/oversigt': typeof OversigtRoute
  '/scores': typeof ScoresRoute
  '/stilling': typeof StillingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historik': typeof HistorikRoute
  '/kanoer': typeof KanoerRoute
  '/opsaetning': typeof OpsaetningRoute
  '/oversigt': typeof OversigtRoute
  '/scores': typeof ScoresRoute
  '/stilling': typeof StillingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/historik'
    | '/kanoer'
    | '/opsaetning'
    | '/oversigt'
    | '/scores'
    | '/stilling'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/historik'
    | '/kanoer'
    | '/opsaetning'
    | '/oversigt'
    | '/scores'
    | '/stilling'
  id:
    | '__root__'
    | '/'
    | '/historik'
    | '/kanoer'
    | '/opsaetning'
    | '/oversigt'
    | '/scores'
    | '/stilling'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistorikRoute: typeof HistorikRoute
  KanoerRoute: typeof KanoerRoute
  OpsaetningRoute: typeof OpsaetningRoute
  OversigtRoute: typeof OversigtRoute
  ScoresRoute: typeof ScoresRoute
  StillingRoute: typeof StillingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historik': {
      id: '/historik'
      path: '/historik'
      fullPath: '/historik'
      preLoaderRoute: typeof HistorikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanoer': {
      id: '/kanoer'
      path: '/kanoer'
      fullPath: '/kanoer'
      preLoaderRoute: typeof KanoerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opsaetning': {
      id: '/opsaetning'
      path: '/opsaetning'
      fullPath: '/opsaetning'
      preLoaderRoute: typeof OpsaetningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oversigt': {
      id: '/oversigt'
      path: '/oversigt'
      fullPath: '/oversigt'
      preLoaderRoute: typeof OversigtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stilling': {
      id: '/stilling'
      path: '/stilling'
      fullPath: '/stilling'
      preLoaderRoute: typeof StillingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistorikRoute: HistorikRoute,
  KanoerRoute: KanoerRoute,
  OpsaetningRoute: OpsaetningRoute,
  OversigtRoute: OversigtRoute,
  ScoresRoute: ScoresRoute,
  StillingRoute: StillingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
